Movie.delete_all
User.delete_all
Vote.delete_all

movies = [
  {name: 'Amour', slug: 'amour', url1: 'https://www.youtube.com/watch?v=H2INylnfMCU', url2: 'http://www.imdb.com/title/tt1602620/', director: 'Michael Haneke', cast: 'Jean-Louis Trintignant, Emmanuelle Riva and Isabelle Huppert', synopsis: 'Georges and Anne are in their eighties. They are cultivated, retired music teachers. Their daughter, who is also a musician, lives abroad with her family. One day, Anne has an attack. The couple\'s bond of love is severely tested.'},
  {name: 'Argo', slug: 'argo', url1: 'https://www.youtube.com/watch?v=ZF7i2n5NXLo', url2: 'http://www.imdb.com/title/tt2125435/', director: 'Benh Zeitlin', cast: 'Quvenzhané Wallis, Dwight Henry and Levy Easterly', synopsis: 'Faced with both her hot-tempered father\'s fading health and melting ice-caps that flood her ramshackle bayou community and unleash ancient aurochs, six-year-old Hushpuppy must learn the ways of courage and love.'},
  {name: 'Beasts of the Southern Wild', slug: 'beasts', url1: 'https://www.youtube.com/watch?v=ZF7i2n5NXLo', url2: 'http://www.imdb.com/title/tt2125435/', director: 'Benh Zeitlin', cast: 'Quvenzhané Wallis, Dwight Henry and Levy Easterly', synopsis: 'Faced with both her hot-tempered father\'s fading health and melting ice-caps that flood her ramshackle bayou community and unleash ancient aurochs, six-year-old Hushpuppy must learn the ways of courage and love.'},
  {name: 'Django Unchained', slug: 'django', url1: 'https://www.youtube.com/watch?v=eUdM9vrCbow', url2: 'http://www.imdb.com/title/tt1853728/', director: 'Quentin Tarantino', cast: 'Jamie Foxx, Christoph Waltz and Leonardo DiCaprio', synopsis: 'With the help of his mentor, a slave-turned-bounty hunter sets out to rescue his wife from a brutal Mississippi plantation owner.'},
  {name: 'Les Misérables', slug: 'les-mis', url1: 'https://www.youtube.com/watch?v=YmvHzCLP6ug', url2: 'http://www.imdb.com/title/tt1707386/', director: 'Tom Hooper', cast: 'Hugh Jackman, Russell Crowe and Anne Hathaway', synopsis: 'In 19th-century France, Jean Valjean, who for decades has been hunted by the ruthless policeman Javert after he breaks parole, agrees to care for factory worker Fantine\'s daughter, Cosette. The fateful decision changes their lives forever.'},
  {name: 'Life of Pi', slug: 'life-pi', url1: 'https://www.youtube.com/watch?v=mZEZ35Fhvuc', url2: 'http://www.imdb.com/title/tt0454876/', director: 'Ang Lee', cast: 'Suraj Sharma, Irrfan Khan and Adil Hussain', synopsis: 'A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery. While cast away, he forms an unexpected connection with another survivor ... a fearsome Bengal tiger.'},
  {name: 'Lincoln', slug: 'lincoln', url1: 'https://www.youtube.com/watch?v=qiSAbAuLhqs', url2: 'http://www.imdb.com/title/tt0443272/', director: 'Steven Spielberg', cast: 'Daniel Day-Lewis, Sally Field and David Strathairn', synopsis: 'As the Civil War continues to rage, America\'s president struggles with continuing carnage on the battlefield and as he fights with many inside his own cabinet on the decision to emancipate the slaves.'},
  {name: 'Silver Linings Playbook', slug: 'silver-linings', url1: 'https://www.youtube.com/watch?v=Lj5_FhLaaQQ', url2: 'http://www.imdb.com/title/tt1045658/', director: 'David O. Russell', cast: 'Bradley Cooper, Jennifer Lawrence and Robert De Niro', synopsis: 'After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own.'},
  {name: 'Zero Dark Thirty', slug: 'zero-dark', url1: 'https://www.youtube.com/watch?v=YxC_JNz5Vbg', url2: 'http://www.imdb.com/title/tt1790885/', director: 'Kathryn Bigelow', cast: 'Jessica Chastain, Joel Edgerton and Chris Pratt', synopsis: 'A chronicle of the decade-long hunt for al-Qaeda terrorist leader Osama bin Laden after the September 2001 attacks, and his death at the hands of the Navy S.E.A.L. Team 6 in May, 2011.'}
]

movies.each {|m| Movie.create!(*[m])}