Movie.delete_all
User.delete_all
Vote.delete_all

movies = [
  {name: 'The Artist', slug: 'the-artist', url1: 'http://trailers.apple.com/trailers/weinstein/theartist/', url2: 'http://www.imdb.com/title/tt1655442/', director: 'Michel Hazanavicius', cast: 'Jean Dujardin, Berenice Bejo, John Goodman, James Cromwell, Penelope Ann Miller, Missi Pyle', synopsis: 'Hollywood 1927. George Valentin (Jean Dujardin) is a silent movie superstar. The advent of the talkies will sound the death knell for his career and see him fall into oblivion. For young extra Peppy Miller (Berenice Bejo), it seems the sky\'s the limit - major movie stardom awaits. The Artist tells the story of their interlinked destinies.'},
  {name: 'The Descendants', slug: 'the-descendants', url1: 'http://trailers.apple.com/trailers/fox_searchlight/thedescendants/', url2: 'http://www.imdb.com/title/tt1033575/', director: 'Alexander Payne', cast: 'George Clooney, Shailene Woodley, Beau Bridges, Robert Forster, Judy Greer, Matthew Lillard, Nick Krause, Amara Miller, Mary Birdsong, Rob Huebel, Patricia Hastie', synopsis: 'From Alexander Payne, the creator of the Oscar-winning Sideways, set in Hawaii, The Descendants is a sometimes humorous, sometimes tragic journey for Matt King (George Clooney) an indifferent husband and father of two girls, who is forced to re-examine his past and embrace his future when his wife suffers a boating accident off of Waikiki. The event leads to a rapprochement with his young daughters while Matt wrestles with a decision to sell the family\'s land handed down from Hawaiian royalty and missionaries.'},
  {name: 'Extremely Loud &amp; Incredibly Close', slug: 'extremely-loud-and-incredibly-close', url1: 'http://trailers.apple.com/trailers/wb/extremelyloudandincrediblyclose/', url2: 'http://www.imdb.com/title/tt0477302/', director: 'Stephen Daldry', cast: 'Tom Hanks, Sandra Bullock, Thomas Horn, Max von Sydow, Viola Davis, John Goodman, Jeffrey Wright', synopsis: 'Drama. Oskar (Thomas Horn) is convinced that his father (Tom Hanks), who died in the 9/11 attacks on the World Trade Center, has left a final message for him hidden somewhere in the city. Feeling disconnected from his grieving mother (Sandra Bullock) and driven by a relentlessly active mind that refuses to believe in things that can\'t be observed, Oskar begins searching New York City for the lock that fits a mysterious key he found in his father\'s closet. His journey through the five boroughs takes him beyond his own loss to a greater understanding of the observable world around him.'},
  {name: 'The Help', slug: 'the-help', url1: 'http://trailers.apple.com/trailers/dreamworks/thehelp/', url2: 'http://www.imdb.com/title/tt1454029/', director: 'Tate Taylor', cast: 'Viola Davis, Bryce Dallas Howard, Octavia Spencer, Emma Stone, Jessica Chastain, Allison Janney, Chris Lowell, Sissy Spacek, Cicely Tyson, Mike Vogel', synopsis: 'The Help stars Emma Stone as Skeeter, Viola Davis as Aibileen and Octavia Spencer as Minny-three very different, extraordinary women in Mississippi during the 1960s, who build an unlikely friendship around a secret writing project that breaks societal rules and puts them all at risk. From their improbable alliance a remarkable sisterhood emerges, instilling all of them with the courage to transcend the lines that define them, and the realization that sometimes those lines are made to be crossed-even if it means bringing everyone in town face-to-face with the changing times.'},
  {name: 'Hugo', slug: 'hugo', url1: 'http://trailers.apple.com/trailers/paramount/hugo/', url2: 'http://www.imdb.com/title/tt0970179/', director: 'Martin Scorsese', cast: 'Asa Butterfield, Chloe Grace Moretz, Sacha Baron Cohen, Ben Kingsley, Jude Law, Ray Winstone, Christopher Lee, Helen McCrory, Richard Griffiths, Frances de la Tour, Emily Mortimer, Michael Stuhlbarg', synopsis: 'Throughout his extraordinary career, Academy Award-wining director Martin Scorsese has brought his unique vision and dazzling gifts to life in a series of unforgettable films. This holiday season the legendary storyteller invites you to join him on a thrilling journey to a magical world with his first-ever 3-D film, based on Brian Selznick\'s award-winning, imaginative New York Times best-seller, "The Invention of Hugo Cabret." Hugo is the astonishing adventure of a wily and resourceful boy whose quest to unlock a secret left to him by his father will transform Hugo and all those around him, and reveal a safe and loving place he can call home.'},
  {name: 'Midnight in Paris', slug: 'midnight-in-paris', url1: 'http://trailers.apple.com/trailers/sony/midnightinparis/', url2: 'http://www.imdb.com/title/tt1605783/', director: 'Woody Allen', cast: 'Kathy Bates, Adrien Brody, Carla Bruni, Marion Cotillard, Rachel McAdams, Michael Sheen, Owen Wilson', synopsis: 'This is a romantic comedy set in Paris about a family that goes there because of business, and two young people who are engaged to be married in the fall have experiences there that change their lives. It\'s about a young man\'s great love for a city, Paris, and the illusion people have that a life different from theirs would be much better. It stars Owen Wilson, Rachel McAdams, Marion Cotillard, Kathy Bates, Carla Bruni, among others.'},
  {name: 'Moneyball', slug: 'moneyball', url1: 'http://trailers.apple.com/trailers/sony_pictures/moneyball/', url2: 'http://www.imdb.com/title/tt1210166/', director: 'Bennett Miller', cast: 'Brad Pitt, Jonah Hill, Philip Seymour Hoffman', synopsis: 'Based on a true story, Moneyball is a movie for anybody who has ever dreamed of taking on the system. Brad Pitt stars as Billy Beane, the general manager of the Oakland A\'s and the guy who assembles the team, who has an epiphany: all of baseball\'s conventional wisdom is wrong. Forced to reinvent his team on a tight budget, Beane will have to outsmart the richer clubs. The onetime jock teams with Ivy League grad Peter Brand (Jonah Hill) in an unlikely partnership, recruiting bargain players that the scouts call flawed, but all of whom have an ability to get on base, score runs, and win games. It\'s more than baseball, it\'s a revolution - one that challenges old school traditions and puts Beane in the crosshairs of those who say he\'s tearing out the heart and soul of the game.'},
  {name: 'The Tree of Life', slug: 'the-tree-of-life', url1: 'http://trailers.apple.com/trailers/fox_searchlight/thetreeoflife/', url2: 'http://www.imdb.com/title/tt0478304/', director: 'Terrence Malick', cast: 'Brad Pitt, Sean Penn, Jessica Chastain', synopsis: 'From Terrence Malick, the acclaimed director of such classic films as Badlands, Days of Heaven and The Thin Red Line, The Tree of Life is the impressionistic story of a Midwestern family in the 1950\'s. The film follows the life journey of the eldest son, Jack, through the innocence of childhood to his disillusioned adult years as he tries to reconcile a complicated relationship with his father (Brad Pitt). Jack (played as an adult by Sean Penn) finds himself a lost soul in the modern world, seeking answers to the origins and meaning of life while questioning the existence of faith. Through Malick\'s signature imagery, we see how both brute nature and spiritual grace shape not only our lives as individuals and families, but all life.'},
  {name: 'War Horse', slug: 'war-horse', url1: 'http://trailers.apple.com/trailers/dreamworks/warhorse/', url2: 'http://www.imdb.com/title/tt1568911/', director: 'Steven Spielberg', cast: 'Emily Watson, David Thewlis, Peter Mullan, Niels Arestrup, Tom Hiddleston, Jeremy Irvine, Benedict Cumberbatch, Toby Kebbell', synopsis: 'Set against a sweeping canvas of rural England and Europe during the First World War, War Horse begins with the remarkable friendship between a horse named Joey and a young man called Albert, who tames and trains him. When they are forcefully parted, the film follows the extraordinary journey of the horse as he moves through the war, changing and inspiring the lives of all those he meets-British cavalry, German soldiers, and a French farmer and his granddaughter-before the story reaches its emotional climax in the heart of No Man\'s Land. The First World War is experienced through the journey of this horse-an odyssey of joy and sorrow, passionate friendship and high adventure.'}
]

movies.each {|m| Movie.create!(*[m])}