Movie.delete_all
User.delete_all
Vote.delete_all

movies = [
  {name: 'American Hustle', slug: 'american-hustle', url1: 'http://oscar.go.com/nominees/best-picture/american-hustle', url2: 'http://www.imdb.com/title/tt1800241/', director: 'David O. Russell', cast: 'Christian Bale, Amy Adams, Bradley Cooper, Jennifer Lawrence, Jeremy Renner', synopsis: 'When small-time con man Irving Rosenfeld meets Sydney Prosser, an ambitious hustler who persuades him to up the stakes in his scams, they find themselves targeted by FBI agent Richie DiMaso. With the threat of prison looming, Irving and Sydney agree to cooperate with DiMaso in a far-reaching sting operation that will target prominent political figures.'},
  {name: 'Nebraska', slug: 'nebraska', url1: 'http://oscar.go.com/nominees/best-picture/nebraska', url2: 'http://www.imdb.com/title/tt1821549/', director: 'Alexander Payne', cast: 'Bruce Dern, Will Forte, June Squibb', synopsis: 'Woody Grant is an obstreperous, hard-drinking man, now elderly and confused, who becomes convinced by a magazine sweepstakes mailer that he has won a million dollars. When he persists in leaving his Montana home in an attempt to walk to Lincoln, Nebraska, and claim his prize, his son David takes him on a road trip that will revisit the sites of his father\'s youth.'},
  {name: 'Captain Phillips', slug: 'captain-phillips', url1: 'http://oscar.go.com/nominees/best-picture/captain-phillips', url2: 'http://www.imdb.com/title/tt1535109/', director: 'Paul Greengrass', cast: 'Tom Hanks, Barkhad Abdi, Barkhad Abdirahman', synopsis: 'When the freighter ship Maersk Alabama is pursued and captured by a handful of Somali pirates, Captain Richard Phillips faces off against Muse, the band\'s leader, in an effort to protect the lives of his crew. In an explosively dangerous situation, Phillips must strike a careful balance between strength and compliance if he and the men he is responsible for are to survive.'},
  {name: 'Philomena', slug: 'philomena', url1: 'http://oscar.go.com/nominees/best-picture/philomena', url2: 'http://www.imdb.com/title/tt2431286/', director: 'Stephen Frears', cast: 'Judi Dench, Steve Coogan, Sophie Kennedy Clark', synopsis: 'When Irishwoman Philomena Lee gave birth to her son in 1952, the boy was taken from her by the Catholic home for unwed mothers to which she had been consigned, and adopted out to a family in America. Accompanied by a former BBC correspondent in search of a human interest story, Philomena travels to Washington, D.C. in an attempt to find her now-grown child.'},
  {name: 'Dallas Buyers Club', slug: 'dallas-buyers-club', url1: 'http://oscar.go.com/nominees/best-picture/dallas-buyers-club', url2: 'http://www.imdb.com/title/tt0790636/', director: 'Jean-Marc Vallee', cast: 'Matthew McConaughey, Jennifer Garner, Jared Leto', synopsis: 'When Ron Woodroof learns he is HIV-positive, the homophobic Texan finds himself sharing an unexpected bond with gay men also battling the illness. Quickly realizing that their only chance of survival lies in making an end run around government regulations and powerful pharmaceutical companies, Ron organizes an illicit trade in a drug cocktail that shows signs of slowing the virus\'s progress.'},
  {name: '12 Years a Slave', slug: 'twelve-years-a-slave', url1: 'http://oscar.go.com/nominees/best-picture/12-years-a-slave', url2: 'http://www.imdb.com/title/tt2024544/', director: 'Steve McQueen', cast: 'Chiwetel Ejiofor, Michael K. Williams, Michael Fassbender', synopsis: 'Solomon Northup, a free black man living with his wife and children in New York in 1841, is tricked by slave traders into traveling to Washington, D.C., where he is kidnapped and sold into slavery. Sent to Louisiana, he experiences the violence and degradation of life as a slave while clinging to the hope that he will someday regain his freedom.'},
  {name: 'Gravity', slug: 'gravity', url1: 'http://oscar.go.com/nominees/best-picture/gravity', url2: 'http://www.imdb.com/title/tt1454468/', director: 'Alfonso Cuaron', cast: 'Sandra Bullock, George Clooney, Ed Harris', synopsis: 'As three members of the shuttle crew work outside the craft to repair the Hubble telescope, they have a catastrophic encounter with a field of space debris. Cut off from all communication with Houston ground control, novice astronaut Dr. Ryan Stone must master her terror and rely on instructions from her veteran flight companion, Matt Kowalski, if she is to survive.'},
  {name: 'The Wolf of Wall Street', slug: 'the-wolf-of-wall-street', url1: 'http://oscar.go.com/nominees/best-picture/the-wolf-of-wall-street', url2: 'http://www.imdb.com/title/tt0993846/', director: 'Martin Scorsese', cast: 'Leonardo DiCaprio, Jonah Hill, Margot Robbie', synopsis: 'In the heady financial world of the 1990s, stockbroker Jordan Belfort enjoys a meteoric rise as one of Wall Street\'s power players. Tossing aside ethics and legality, he embraces the excesses of the era and enters into a series of scams that will have far-reaching implications throughout the financial community.'},
  {name: 'Her', slug: 'her', url1: 'http://oscar.go.com/nominees/best-picture/her', url2: 'http://www.imdb.com/title/tt1798709/', director: 'Spike Jonze', cast: 'Joaquin Phoenix, Amy Adams, Scarlett Johansson', synopsis: 'In a future when most of society\'s problems have been resolved, the search for companionship continues. For Theodore, a recently divorced writer of other people\'s love letters, the possibility of love arises from an unexpected quarter: an artificial intelligence computer operating system known as Samantha.'}
]

movies.each {|m| Movie.create!(*[m])}